let BtnAboutTheCompany = document.getElementById("btn-about-the-company")
let BtnDiveryAndPayment = document.getElementById("btn-delivery-and-payment")
let BtnContacts = document.getElementById("btn-contacts")
let WraperMain = document.getElementById("wraper_Main")
let wrapertest = document.getElementById("wraper-test")
let btntest = document.getElementById("btn-test")
let AboutTheCompanyBtn = document.getElementById("about-the-company-btn")
let DeliveryAndPaymentBtn = document.getElementById("delivery-and-payment-btn")
let ContactsBtn = document.getElementById("contacts-btn")
let HeadingAboutTheCompany = document.getElementById("heading-about-the-company")
let HeadingDeliveryAndPayment = document.getElementById("heading-delivery-and-payment")
let HeadingContacts = document.getElementById("heading-contacts")
let WraperOpenCertificate = document.getElementById("wraper-open-certificate")
let PhotoAboutTheCompanyBlockOfText = document.getElementById("photo-about-the-company-block-of-text")
let BtnMagnifierSvg = document.getElementById("btn-magnifier-svg")
let ButtonCloseCertificate = document.getElementById("button_close-certificate")
let WraperBlokDeliveryAndPayment = document.getElementById("wraper-blok-delivery-and-payment")
let WraperContacts = document.getElementById("wraper-contacts")
let headingSawmill = document.getElementById("heading-Sawmill")
let headinglezhnevka = document.getElementById("heading-lezhnevka")
let headingCharcoal = document.getElementById("heading-Charcoal")
let headingLumber = document.getElementById("heading-Lumber")
let headingEuropoddons = document.getElementById("heading-Europoddons")
// ---
let catologSawmill = document.getElementById("catolog-Sawmill")
let catologLezhnevka = document.getElementById("catolog-Lezhnevka")
let catologCharcoal = document.getElementById("catolog-Charcoal")
let catologLumber = document.getElementById("catolog-Lumber")
let catologEuropoddons = document.getElementById("catolog-Europoddons")
let wrapercatolog = document.getElementById("wraper-catolog")
let HeaderDownMenutext1 = document.getElementById("header-down-menu-text1")
let HeaderDownMenutext2 = document.getElementById("header-down-menu-text2")
let HeaderDownMenutext3 = document.getElementById("header-down-menu-text3")
let HeaderDownMenutext4 = document.getElementById("header-down-menu-text4")
let HeaderDownMenutext5 = document.getElementById("header-down-menu-text5")
let btnGoingToTheCatalogNeedles = document.getElementById("btn_going-to-the-catalog-needles")
let btnGoingToTheCatalogCoal = document.getElementById("btn_going-to-the-catalog-coal")
let btnGoingToTheCatalogLumber = document.getElementById("btn_going-to-the-catalog-lumber")
let btnGoingToTheCatalogEuropoddons = document.getElementById("btn_going-to-the-catalog-europoddons")
let btnGoingToTheCatalogLezhnevka = document.getElementById("btn_going-to-the-catalog-lezhnevka")
let btnCategoriesCoal = document.getElementById("btn-categories-Coal")
let btnCategoriesEuropoddons = document.getElementById("btn-categories-Europoddons")
let btnCategoriesLezhnevka = document.getElementById("btn-categories-Lezhnevka")
let btnCategoriesLumber = document.getElementById("btn-categories-Lumber")
let btnMoreDetailed = document.getElementById("btn-more-detailed")
let ButtonSubmitYourApplication = document.getElementById("button-Submit-your-application")



// ------действие на второстепенной странице

ButtonCloseCertificate.addEventListener('click', function () {
    WraperOpenCertificate.classList.remove("wraper-open-certificate-show")
    PhotoAboutTheCompanyBlockOfText.classList.add("photo-about-the-company-block-of-text_show")

    return (0)
})

BtnMagnifierSvg.addEventListener('click', function () {
    WraperOpenCertificate.classList.add("wraper-open-certificate-show")
    PhotoAboutTheCompanyBlockOfText.classList.remove("photo-about-the-company-block-of-text_show")
    return (0)
})

HeaderDownMenutext1.addEventListener('click', function () {
    headingSawmill.classList.add("heading-Sawmill-show")
    wrapercatolog.classList.add("wraper-catolog-show")
    catologSawmill.classList.add("catolog-Sawmill-show")
    WraperOpenCertificate.classList.remove("wraper-open-certificate-show")
    HeadingAboutTheCompany.classList.remove("heading-about-the-company-show")
    PhotoAboutTheCompanyBlockOfText.classList.remove("photo-about-the-company-block-of-text_show")
    HeadingDeliveryAndPayment.classList.remove("heading-delivery-and-payment-show")
    HeadingContacts.classList.remove("heading-contacts-show")
    catologLezhnevka.classList.remove("catolog-Lezhnevka-show")
    headinglezhnevka.classList.remove("heading-lezhnevka-show")
    WraperBlokDeliveryAndPayment.classList.remove("wraper-blok-delivery-and-payment-show")
    headingCharcoal.classList.remove("heading-Charcoal-show")
    catologCharcoal.classList.remove("catolog-Charcoal-show")
    headingLumber.classList.remove("heading-Lumber-show")
    catologLumber.classList.remove("catolog-Lumber-show")
    headingEuropoddons.classList.remove("heading-Europoddons-show")
    catologEuropoddons.classList.remove("catolog-Europoddons-show")
    headingError.classList.remove("heading-error-show")
    return (0)
})






HeaderDownMenutext2.addEventListener('click', function () {
    headinglezhnevka.classList.add("heading-lezhnevka-show")
    catologLezhnevka.classList.add("catolog-Lezhnevka-show")
    wrapercatolog.classList.add("wraper-catolog-show")
    WraperOpenCertificate.classList.remove("wraper-open-certificate-show")
    catologSawmill.classList.remove("catolog-Sawmill-show")
    headingSawmill.classList.remove("heading-Sawmill-show")
    HeadingAboutTheCompany.classList.remove("heading-about-the-company-show")
    PhotoAboutTheCompanyBlockOfText.classList.remove("photo-about-the-company-block-of-text_show")
    HeadingDeliveryAndPayment.classList.remove("heading-delivery-and-payment-show")
    WraperBlokDeliveryAndPayment.classList.remove("wraper-blok-delivery-and-payment-show")
    HeadingContacts.classList.remove("heading-contacts-show")
    WraperContacts.classList.remove("wraper-contacts-show")
    headingCharcoal.classList.remove("heading-Charcoal-show")
    catologCharcoal.classList.remove("catolog-Charcoal-show")
    headingLumber.classList.remove("heading-Lumber-show")
    catologLumber.classList.remove("catolog-Lumber-show")
    headingEuropoddons.classList.remove("heading-Europoddons-show")
    catologEuropoddons.classList.remove("catolog-Europoddons-show")
    headingError.classList.remove("heading-error-show")
    return (0)
})

HeaderDownMenutext3.addEventListener('click', function () {
    headingCharcoal.classList.add("heading-Charcoal-show")
    catologCharcoal.classList.add("catolog-Charcoal-show")
    wrapercatolog.classList.add("wraper-catolog-show")
    WraperOpenCertificate.classList.remove("wraper-open-certificate-show")
    catologLezhnevka.classList.remove("catolog-Lezhnevka-show")
    catologSawmill.classList.remove("catolog-Sawmill-show")
    headingSawmill.classList.remove("heading-Sawmill-show")
    HeadingAboutTheCompany.classList.remove("heading-about-the-company-show")
    HeadingDeliveryAndPayment.classList.remove("heading-delivery-and-payment-show")
    HeadingContacts.classList.remove("heading-contacts-show")
    headinglezhnevka.classList.remove("heading-lezhnevka-show")
    PhotoAboutTheCompanyBlockOfText.classList.remove("photo-about-the-company-block-of-text_show")
    WraperBlokDeliveryAndPayment.classList.remove("wraper-blok-delivery-and-payment-show")
    WraperContacts.classList.remove("wraper-contacts-show")
    headingLumber.classList.remove("heading-Lumber-show")
    catologLumber.classList.remove("catolog-Lumber-show")
    headingEuropoddons.classList.remove("heading-Europoddons-show")
    catologEuropoddons.classList.remove("catolog-Europoddons-show")
    headingError.classList.remove("heading-error-show")
    return (0)
})



HeaderDownMenutext4.addEventListener('click', function () {
    headingLumber.classList.add("heading-Lumber-show")
    catologLumber.classList.add("catolog-Lumber-show")
    wrapercatolog.classList.add("wraper-catolog-show")
    WraperOpenCertificate.classList.remove("wraper-open-certificate-show")
    HeadingAboutTheCompany.classList.remove("heading-about-the-company-show")
    HeadingDeliveryAndPayment.classList.remove("heading-delivery-and-payment-show")
    HeadingContacts.classList.remove("heading-contacts-show")
    headingCharcoal.classList.remove("heading-Charcoal-show")
    headinglezhnevka.classList.remove("heading-lezhnevka-show")
    headingSawmill.classList.remove("heading-Sawmill-show")
    PhotoAboutTheCompanyBlockOfText.classList.remove("photo-about-the-company-block-of-text_show")
    WraperBlokDeliveryAndPayment.classList.remove("wraper-blok-delivery-and-payment-show")
    WraperContacts.classList.remove("wraper-contacts-show")
    catologLezhnevka.classList.remove("catolog-Lezhnevka-show")
    catologSawmill.classList.remove("catolog-Sawmill-show")
    catologCharcoal.classList.remove("catolog-Charcoal-show")
    headingEuropoddons.classList.remove("heading-Europoddons-show")
    catologEuropoddons.classList.remove("catolog-Europoddons-show")
    headingError.classList.remove("heading-error-show")
    return (0)

})

HeaderDownMenutext5.addEventListener('click', function () {
    headingEuropoddons.classList.add("heading-Europoddons-show")
    catologEuropoddons.classList.add("catolog-Europoddons-show")
    wrapercatolog.classList.add("wraper-catolog-show")
    WraperOpenCertificate.classList.remove("wraper-open-certificate-show")
    HeadingAboutTheCompany.classList.remove("heading-about-the-company-show")
    HeadingDeliveryAndPayment.classList.remove("heading-delivery-and-payment-show")
    HeadingContacts.classList.remove("heading-contacts-show")
    headingCharcoal.classList.remove("heading-Charcoal-show")
    headinglezhnevka.classList.remove("heading-lezhnevka-show")
    headingSawmill.classList.remove("heading-Sawmill-show")
    headingLumber.classList.remove("heading-Lumber-show")
    catologLezhnevka.classList.remove("catolog-Lezhnevka-show")
    catologSawmill.classList.remove("catolog-Sawmill-show")
    catologCharcoal.classList.remove("catolog-Charcoal-show")
    catologLumber.classList.remove("catolog-Lumber-show")
    PhotoAboutTheCompanyBlockOfText.classList.remove("photo-about-the-company-block-of-text_show")
    WraperBlokDeliveryAndPayment.classList.remove("wraper-blok-delivery-and-payment-show")
    WraperContacts.classList.remove("wraper-contacts-show")
    headingError.classList.remove("heading-error-show")
    return (0)
})




AboutTheCompanyBtn.addEventListener('click', function () {
    WraperOpenCertificate.classList.remove("wraper-open-certificate-show")
    PhotoAboutTheCompanyBlockOfText.classList.add("photo-about-the-company-block-of-text_show")
    HeadingAboutTheCompany.classList.add("heading-about-the-company-show")
    HeadingDeliveryAndPayment.classList.remove("heading-delivery-and-payment-show")
    HeadingContacts.classList.remove("heading-contacts-show")
    WraperBlokDeliveryAndPayment.classList.remove("wraper-blok-delivery-and-payment-show")
    WraperContacts.classList.remove("wraper-contacts-show")
    headingSawmill.classList.remove("heading-Sawmill-show")
    wrapercatolog.classList.remove("wraper-catolog-show")
    catologSawmill.classList.remove("catolog-Sawmill-show")
    headinglezhnevka.classList.remove("heading-lezhnevka-show")
    catologLezhnevka.classList.remove("catolog-Lezhnevka-show")
    headingCharcoal.classList.remove("heading-Charcoal-show")
    catologCharcoal.classList.remove("catolog-Charcoal-show")
    headingLumber.classList.remove("heading-Lumber-show")
    catologLumber.classList.remove("catolog-Lumber-show")
    headingEuropoddons.classList.remove("heading-Europoddons-show")
    catologEuropoddons.classList.remove("catolog-Europoddons-show")
    headingError.classList.remove("heading-error-show")
    return (0)
})

DeliveryAndPaymentBtn.addEventListener('click', function () {
    WraperBlokDeliveryAndPayment.classList.add("wraper-blok-delivery-and-payment-show")
    WraperOpenCertificate.classList.remove("wraper-open-certificate-show")
    PhotoAboutTheCompanyBlockOfText.classList.remove("photo-about-the-company-block-of-text_show")
    HeadingDeliveryAndPayment.classList.add("heading-delivery-and-payment-show")
    HeadingAboutTheCompany.classList.remove("heading-about-the-company-show")
    HeadingContacts.classList.remove("heading-contacts-show")
    WraperContacts.classList.remove("wraper-contacts-show")
    headingSawmill.classList.remove("heading-Sawmill-show")
    wrapercatolog.classList.remove("wraper-catolog-show")
    catologSawmill.classList.remove("catolog-Sawmill-show")
    headinglezhnevka.classList.remove("heading-lezhnevka-show")
    catologLezhnevka.classList.remove("catolog-Lezhnevka-show")
    catologCharcoal.classList.remove("catolog-Charcoal-show")
    headingCharcoal.classList.remove("heading-Charcoal-show")
    headingLumber.classList.remove("heading-Lumber-show")
    catologLumber.classList.remove("catolog-Lumber-show")
    headingEuropoddons.classList.remove("heading-Europoddons-show")
    catologEuropoddons.classList.remove("catolog-Europoddons-show")
    headingError.classList.remove("heading-error-show")
    return (0)
})

ContactsBtn.addEventListener('click', function () {
    WraperContacts.classList.add("wraper-contacts-show")
    PhotoAboutTheCompanyBlockOfText.classList.remove("photo-about-the-company-block-of-text_show")
    WraperOpenCertificate.classList.remove("wraper-open-certificate-show")
    HeadingContacts.classList.add("heading-contacts-show")
    HeadingAboutTheCompany.classList.remove("heading-about-the-company-show")
    HeadingDeliveryAndPayment.classList.remove("heading-delivery-and-payment-show")
    WraperBlokDeliveryAndPayment.classList.remove("wraper-blok-delivery-and-payment-show")
    headingSawmill.classList.remove("heading-Sawmill-show")
    wrapercatolog.classList.remove("wraper-catolog-show")
    catologSawmill.classList.remove("catolog-Sawmill-show")
    headinglezhnevka.classList.remove("heading-lezhnevka-show")
    catologLezhnevka.classList.remove("catolog-Lezhnevka-show")
    headingCharcoal.classList.remove("heading-Charcoal-show")
    catologCharcoal.classList.remove("catolog-Charcoal-show")
    headingLumber.classList.remove("heading-Lumber-show")
    catologLumber.classList.remove("catolog-Lumber-show")
    headingEuropoddons.classList.remove("heading-Europoddons-show")
    catologEuropoddons.classList.remove("catolog-Europoddons-show")
    headingError.classList.remove("heading-error-show")
    return (0)

})


// ----переход с главной страницы

ButtonSubmitYourApplication.addEventListener('click', function () {
    HeadingContacts.classList.add("heading-contacts-show")
    WraperMain.classList.add("wraper_Main_show")
    wrapertest.classList.add("wraper-company_show")
    WraperBlokDeliveryAndPayment.classList.remove("wraper-blok-delivery-and-payment-show")
    WraperContacts.classList.add("wraper-contacts-show")
    headinglezhnevka.classList.remove("heading-lezhnevka-show")
    catologLezhnevka.classList.remove("catolog-Lezhnevka-show")
    headingCharcoal.classList.remove("heading-Charcoal-show")
    catologCharcoal.classList.remove("catolog-Charcoal-show")
    WraperOpenCertificate.classList.remove("wraper-open-certificate-show")
    headingLumber.classList.remove("heading-Lumber-show")
    catologLumber.classList.remove("catolog-Lumber-show")
    headingEuropoddons.classList.remove("heading-Europoddons-show")
    catologEuropoddons.classList.remove("catolog-Europoddons-show")
    headingError.classList.remove("heading-error-show")
    return (0)

})


btnMoreDetailed.addEventListener("click", function () {
    HeadingAboutTheCompany.classList.add("heading-about-the-company-show")
    // WraperOpenCertificate.classList.add('wraper-open-certificate-show')
    PhotoAboutTheCompanyBlockOfText.classList.add("photo-about-the-company-block-of-text_show")
    WraperMain.classList.add("wraper_Main_show")
    wrapertest.classList.add("wraper-company_show")
    WraperBlokDeliveryAndPayment.classList.remove("wraper-blok-delivery-and-payment-show")
    WraperContacts.classList.remove("wraper-contacts-show")
    headinglezhnevka.classList.remove("heading-lezhnevka-show")
    catologLezhnevka.classList.remove("catolog-Lezhnevka-show")
    headingCharcoal.classList.remove("heading-Charcoal-show")
    catologCharcoal.classList.remove("catolog-Charcoal-show")
    WraperOpenCertificate.classList.remove("wraper-open-certificate-show")
    headingLumber.classList.remove("heading-Lumber-show")
    catologLumber.classList.remove("catolog-Lumber-show")
    headingEuropoddons.classList.remove("heading-Europoddons-show")
    catologEuropoddons.classList.remove("catolog-Europoddons-show")
    headingError.classList.remove("heading-error-show")
    return (0)
})


btnCategoriesCoal.addEventListener('click', function () {
    headingCharcoal.classList.add("heading-Charcoal-show")
    wrapercatolog.classList.add("wraper-catolog-show")
    catologCharcoal.classList.add("catolog-Charcoal-show")
    WraperMain.classList.add("wraper_Main_show")
    wrapertest.classList.add("wraper-company_show")
    headingError.classList.remove("heading-error-show")
    return (0)

})

btnCategoriesEuropoddons.addEventListener('click', function () {
    headingEuropoddons.classList.add("heading-Europoddons-show")
    wrapercatolog.classList.add("wraper-catolog-show")
    catologEuropoddons.classList.add("catolog-Europoddons-show")
    WraperMain.classList.add("wraper_Main_show")
    wrapertest.classList.add("wraper-company_show")
    headingError.classList.remove("heading-error-show")
    return (0)
})

btnCategoriesLezhnevka.addEventListener('click', function () {
    headinglezhnevka.classList.add("heading-lezhnevka-show")
    catologLezhnevka.classList.add("catolog-Lezhnevka-show")
    wrapercatolog.classList.add("wraper-catolog-show")
    WraperMain.classList.add("wraper_Main_show")
    wrapertest.classList.add("wraper-company_show")
    headingError.classList.remove("heading-error-show")
    return (0)
})

btnCategoriesLumber.addEventListener('click', function () {
    headingLumber.classList.add("heading-Lumber-show")
    catologLumber.classList.add("catolog-Lumber-show")
    wrapercatolog.classList.add("wraper-catolog-show")
    WraperMain.classList.add("wraper_Main_show")
    wrapertest.classList.add("wraper-company_show")
    headingError.classList.remove("heading-error-show")
    return (0)
})


btnGoingToTheCatalogNeedles.addEventListener('click', function () {
    headingSawmill.classList.add("heading-Sawmill-show")
    wrapercatolog.classList.add("wraper-catolog-show")
    catologSawmill.classList.add("catolog-Sawmill-show")
    WraperMain.classList.add("wraper_Main_show")
    wrapertest.classList.add("wraper-company_show")
    headingError.classList.remove("heading-error-show")
    return (0)
})


btnGoingToTheCatalogCoal.addEventListener('click', function () {
    headingCharcoal.classList.add("heading-Charcoal-show")
    wrapercatolog.classList.add("wraper-catolog-show")
    catologCharcoal.classList.add("catolog-Charcoal-show")
    WraperMain.classList.add("wraper_Main_show")
    wrapertest.classList.add("wraper-company_show")
    headingError.classList.remove("heading-error-show")
    return (0)

})

btnGoingToTheCatalogLumber.addEventListener('click', function () {
    headingLumber.classList.add("heading-Lumber-show")
    wrapercatolog.classList.add("wraper-catolog-show")
    catologLumber.classList.add("catolog-Lumber-show")
    WraperMain.classList.add("wraper_Main_show")
    wrapertest.classList.add("wraper-company_show")
    headingError.classList.remove("heading-error-show")
    return (0)
})

btnGoingToTheCatalogEuropoddons.addEventListener('click', function () {
    headingEuropoddons.classList.add("heading-Europoddons-show")
    wrapercatolog.classList.add("wraper-catolog-show")
    catologEuropoddons.classList.add("catolog-Europoddons-show")
    WraperMain.classList.add("wraper_Main_show")
    wrapertest.classList.add("wraper-company_show")
    headingError.classList.remove("heading-error-show")
    return (0)
})

btnGoingToTheCatalogLezhnevka.addEventListener('click', function () {
    headinglezhnevka.classList.add("heading-lezhnevka-show")
    catologLezhnevka.classList.add("catolog-Lezhnevka-show")
    wrapercatolog.classList.add("wraper-catolog-show")
    WraperMain.classList.add("wraper_Main_show")
    wrapertest.classList.add("wraper-company_show")
    headingError.classList.remove("heading-error-show")
    return (0)
})





BtnAboutTheCompany.addEventListener('click', function () {
    HeadingAboutTheCompany.classList.add("heading-about-the-company-show")
    // WraperOpenCertificate.classList.add('wraper-open-certificate-show')
    PhotoAboutTheCompanyBlockOfText.classList.add("photo-about-the-company-block-of-text_show")
    WraperMain.classList.add("wraper_Main_show")
    wrapertest.classList.add("wraper-company_show")
    WraperBlokDeliveryAndPayment.classList.remove("wraper-blok-delivery-and-payment-show")
    WraperContacts.classList.remove("wraper-contacts-show")
    headinglezhnevka.classList.remove("heading-lezhnevka-show")
    catologLezhnevka.classList.remove("catolog-Lezhnevka-show")
    headingCharcoal.classList.remove("heading-Charcoal-show")
    catologCharcoal.classList.remove("catolog-Charcoal-show")
    WraperOpenCertificate.classList.remove("wraper-open-certificate-show")
    headingLumber.classList.remove("heading-Lumber-show")
    catologLumber.classList.remove("catolog-Lumber-show")
    headingEuropoddons.classList.remove("heading-Europoddons-show")
    catologEuropoddons.classList.remove("catolog-Europoddons-show")
    headingError.classList.remove("heading-error-show")
    // error.classList.remove("wraper-Error-show")

    return (0)

})

BtnDiveryAndPayment.addEventListener('click', function () {
    WraperBlokDeliveryAndPayment.classList.add("wraper-blok-delivery-and-payment-show")
    HeadingDeliveryAndPayment.classList.add("heading-delivery-and-payment-show")
    WraperMain.classList.add("wraper_Main_show")
    wrapertest.classList.add("wraper-company_show")
    WraperContacts.classList.remove("wraper-contacts-show")
    headinglezhnevka.classList.remove("heading-lezhnevka-show")
    catologLezhnevka.classList.remove("catolog-Lezhnevka-show")
    headingCharcoal.classList.remove("heading-Charcoal-show")
    catologCharcoal.classList.remove("catolog-Charcoal-show")
    WraperOpenCertificate.classList.remove("wraper-open-certificate-show")
    headingLumber.classList.remove("heading-Lumber-show")
    catologLumber.classList.remove("catolog-Lumber-show")
    headingEuropoddons.classList.remove("heading-Europoddons-show")
    catologEuropoddons.classList.remove("catolog-Europoddons-show")
    headingError.classList.remove("heading-error-show")
    // error.classList.remove("wraper-Error-show")
    return (0)
})

BtnContacts.addEventListener('click', function () {

    HeadingContacts.classList.add("heading-contacts-show")
    WraperMain.classList.add("wraper_Main_show")
    wrapertest.classList.add("wraper-company_show")
    WraperBlokDeliveryAndPayment.classList.remove("wraper-blok-delivery-and-payment-show")
    WraperContacts.classList.add("wraper-contacts-show")
    headinglezhnevka.classList.remove("heading-lezhnevka-show")
    catologLezhnevka.classList.remove("catolog-Lezhnevka-show")
    headingCharcoal.classList.remove("heading-Charcoal-show")
    catologCharcoal.classList.remove("catolog-Charcoal-show")
    WraperOpenCertificate.classList.remove("wraper-open-certificate-show")
    headingLumber.classList.remove("heading-Lumber-show")
    catologLumber.classList.remove("catolog-Lumber-show")
    headingEuropoddons.classList.remove("heading-Europoddons-show")
    catologEuropoddons.classList.remove("catolog-Europoddons-show")
    headingError.classList.remove("heading-error-show")
    // error.classList.remove("wraper-Error-show")


    return (0)
})







//-------переход на главную сртраницу 
btntest.addEventListener('click', function () {
    headingSawmill.classList.remove("heading-Sawmill-show")
    wrapercatolog.classList.remove("wraper-catolog-show")
    catologSawmill.classList.remove("catolog-Sawmill-show")
    PhotoAboutTheCompanyBlockOfText.classList.remove("photo-about-the-company-block-of-text_show")
    HeadingAboutTheCompany.classList.remove("heading-about-the-company-show")
    HeadingDeliveryAndPayment.classList.remove("heading-delivery-and-payment-show")
    HeadingContacts.classList.remove("heading-contacts-show")
    wrapertest.classList.remove("wraper-company_show")
    WraperMain.classList.remove("wraper_Main_show")
    WraperBlokDeliveryAndPayment.classList.remove("wraper-blok-delivery-and-payment-show")
    WraperContacts.classList.remove("wraper-contacts-show")
    headinglezhnevka.classList.remove("heading-lezhnevka-show")
    catologLezhnevka.classList.remove("catolog-Lezhnevka-show")
    headingCharcoal.classList.remove("heading-Charcoal-show")
    catologCharcoal.classList.remove("catolog-Charcoal-show")
    WraperOpenCertificate.classList.remove("wraper-open-certificate-show")
    headingLumber.classList.remove("heading-Lumber-show")
    catologLumber.classList.remove("catolog-Lumber-show")
    headingEuropoddons.classList.remove("heading-Europoddons-show")
    catologEuropoddons.classList.remove("catolog-Europoddons-show")

    return (0)
})

let headingError = document.getElementById("heading-error")
let inputText = document.getElementById("input-text")
let btnInput = document.getElementById("btn-input")
let error = document.getElementById("wraper-Error")
let test = document.getElementById("test")


btnInput.addEventListener('click', function (e) {
    switch (inputText.value) {
        case "о компании":
            HeadingAboutTheCompany.classList.add("heading-about-the-company-show")
            // WraperOpenCertificate.classList.add('wraper-open-certificate-show')
            HeadingContacts.classList.remove("heading-contacts-show")
            PhotoAboutTheCompanyBlockOfText.classList.add("photo-about-the-company-block-of-text_show")
            WraperMain.classList.add("wraper_Main_show")
            wrapertest.classList.add("wraper-company_show")
            WraperBlokDeliveryAndPayment.classList.remove("wraper-blok-delivery-and-payment-show")
            WraperContacts.classList.remove("wraper-contacts-show")
            headinglezhnevka.classList.remove("heading-lezhnevka-show")
            catologLezhnevka.classList.remove("catolog-Lezhnevka-show")
            headingCharcoal.classList.remove("heading-Charcoal-show")
            catologCharcoal.classList.remove("catolog-Charcoal-show")
            WraperOpenCertificate.classList.remove("wraper-open-certificate-show")
            headingLumber.classList.remove("heading-Lumber-show")
            catologLumber.classList.remove("catolog-Lumber-show")
            headingEuropoddons.classList.remove("heading-Europoddons-show")
            catologEuropoddons.classList.remove("catolog-Europoddons-show")
            headingError.classList.remove("heading-error-show")
            wrapercatolog.classList.remove("wraper-catolog-show")
            break;

        case "доставка":
            WraperBlokDeliveryAndPayment.classList.add("wraper-blok-delivery-and-payment-show")
            HeadingDeliveryAndPayment.classList.add("heading-delivery-and-payment-show")
            WraperMain.classList.add("wraper_Main_show")
            wrapertest.classList.add("wraper-company_show")
            WraperContacts.classList.remove("wraper-contacts-show")
            headinglezhnevka.classList.remove("heading-lezhnevka-show")
            catologLezhnevka.classList.remove("catolog-Lezhnevka-show")
            headingCharcoal.classList.remove("heading-Charcoal-show")
            catologCharcoal.classList.remove("catolog-Charcoal-show")
            WraperOpenCertificate.classList.remove("wraper-open-certificate-show")
            headingLumber.classList.remove("heading-Lumber-show")
            catologLumber.classList.remove("catolog-Lumber-show")
            headingEuropoddons.classList.remove("heading-Europoddons-show")
            catologEuropoddons.classList.remove("catolog-Europoddons-show")
            headingError.classList.remove("heading-error-show")
            headingSawmill.classList.remove("heading-Sawmill-show")
            wrapercatolog.classList.remove("wraper-catolog-show")
            break;
        case "контакты":
            HeadingContacts.classList.add("heading-contacts-show")
            WraperMain.classList.add("wraper_Main_show")
            wrapertest.classList.add("wraper-company_show")
            WraperContacts.classList.add("wraper-contacts-show")
            wrapercatolog.classList.remove("wraper-catolog-show")
            catologSawmill.classList.remove("catolog-Sawmill-show")
            PhotoAboutTheCompanyBlockOfText.classList.remove("photo-about-the-company-block-of-text_show")
            HeadingAboutTheCompany.classList.remove("heading-about-the-company-show")
            HeadingDeliveryAndPayment.classList.remove("heading-delivery-and-payment-show")
            WraperBlokDeliveryAndPayment.classList.remove("wraper-blok-delivery-and-payment-show")
            headinglezhnevka.classList.remove("heading-lezhnevka-show")
            catologLezhnevka.classList.remove("catolog-Lezhnevka-show")
            headingCharcoal.classList.remove("heading-Charcoal-show")
            catologCharcoal.classList.remove("catolog-Charcoal-show")
            WraperOpenCertificate.classList.remove("wraper-open-certificate-show")
            headingLumber.classList.remove("heading-Lumber-show")
            catologLumber.classList.remove("catolog-Lumber-show")
            headingEuropoddons.classList.remove("heading-Europoddons-show")
            catologEuropoddons.classList.remove("catolog-Europoddons-show")
            headingError.classList.remove("heading-error-show")
            break;
        case "пиловочник хвойных пород":
            headingSawmill.classList.add("heading-Sawmill-show")
            wrapercatolog.classList.add("wraper-catolog-show")
            catologSawmill.classList.add("catolog-Sawmill-show")
            WraperOpenCertificate.classList.remove("wraper-open-certificate-show")
            HeadingAboutTheCompany.classList.remove("heading-about-the-company-show")
            PhotoAboutTheCompanyBlockOfText.classList.remove("photo-about-the-company-block-of-text_show")
            HeadingDeliveryAndPayment.classList.remove("heading-delivery-and-payment-show")
            HeadingContacts.classList.remove("heading-contacts-show")
            catologLezhnevka.classList.remove("catolog-Lezhnevka-show")
            headinglezhnevka.classList.remove("heading-lezhnevka-show")
            WraperBlokDeliveryAndPayment.classList.remove("wraper-blok-delivery-and-payment-show")
            headingCharcoal.classList.remove("heading-Charcoal-show")
            catologCharcoal.classList.remove("catolog-Charcoal-show")
            headingLumber.classList.remove("heading-Lumber-show")
            catologLumber.classList.remove("catolog-Lumber-show")
            headingEuropoddons.classList.remove("heading-Europoddons-show")
            catologEuropoddons.classList.remove("catolog-Europoddons-show")
            headingError.classList.remove("heading-error-show")
            break;
        case "лежнёвка":
            headinglezhnevka.classList.add("heading-lezhnevka-show")
            catologLezhnevka.classList.add("catolog-Lezhnevka-show")
            wrapercatolog.classList.add("wraper-catolog-show")
            WraperOpenCertificate.classList.remove("wraper-open-certificate-show")
            catologSawmill.classList.remove("catolog-Sawmill-show")
            headingSawmill.classList.remove("heading-Sawmill-show")
            HeadingAboutTheCompany.classList.remove("heading-about-the-company-show")
            PhotoAboutTheCompanyBlockOfText.classList.remove("photo-about-the-company-block-of-text_show")
            HeadingDeliveryAndPayment.classList.remove("heading-delivery-and-payment-show")
            WraperBlokDeliveryAndPayment.classList.remove("wraper-blok-delivery-and-payment-show")
            HeadingContacts.classList.remove("heading-contacts-show")
            WraperContacts.classList.remove("wraper-contacts-show")
            headingCharcoal.classList.remove("heading-Charcoal-show")
            catologCharcoal.classList.remove("catolog-Charcoal-show")
            headingLumber.classList.remove("heading-Lumber-show")
            catologLumber.classList.remove("catolog-Lumber-show")
            headingEuropoddons.classList.remove("heading-Europoddons-show")
            catologEuropoddons.classList.remove("catolog-Europoddons-show")
            headingError.classList.remove("heading-error-show")
            break;
        case "уголь":
            headingCharcoal.classList.add("heading-Charcoal-show")
            catologCharcoal.classList.add("catolog-Charcoal-show")
            wrapercatolog.classList.add("wraper-catolog-show")
            WraperOpenCertificate.classList.remove("wraper-open-certificate-show")
            catologLezhnevka.classList.remove("catolog-Lezhnevka-show")
            catologSawmill.classList.remove("catolog-Sawmill-show")
            headingSawmill.classList.remove("heading-Sawmill-show")
            HeadingAboutTheCompany.classList.remove("heading-about-the-company-show")
            HeadingDeliveryAndPayment.classList.remove("heading-delivery-and-payment-show")
            HeadingContacts.classList.remove("heading-contacts-show")
            headinglezhnevka.classList.remove("heading-lezhnevka-show")
            PhotoAboutTheCompanyBlockOfText.classList.remove("photo-about-the-company-block-of-text_show")
            WraperBlokDeliveryAndPayment.classList.remove("wraper-blok-delivery-and-payment-show")
            WraperContacts.classList.remove("wraper-contacts-show")
            headingLumber.classList.remove("heading-Lumber-show")
            catologLumber.classList.remove("catolog-Lumber-show")
            headingEuropoddons.classList.remove("heading-Europoddons-show")
            catologEuropoddons.classList.remove("catolog-Europoddons-show")
            headingError.classList.remove("heading-error-show")
            break;
        case "пиломатериалы":
            headingLumber.classList.add("heading-Lumber-show")
            catologLumber.classList.add("catolog-Lumber-show")
            wrapercatolog.classList.add("wraper-catolog-show")
            WraperOpenCertificate.classList.remove("wraper-open-certificate-show")
            HeadingAboutTheCompany.classList.remove("heading-about-the-company-show")
            HeadingDeliveryAndPayment.classList.remove("heading-delivery-and-payment-show")
            HeadingContacts.classList.remove("heading-contacts-show")
            headingCharcoal.classList.remove("heading-Charcoal-show")
            headinglezhnevka.classList.remove("heading-lezhnevka-show")
            headingSawmill.classList.remove("heading-Sawmill-show")
            PhotoAboutTheCompanyBlockOfText.classList.remove("photo-about-the-company-block-of-text_show")
            WraperBlokDeliveryAndPayment.classList.remove("wraper-blok-delivery-and-payment-show")
            WraperContacts.classList.remove("wraper-contacts-show")
            catologLezhnevka.classList.remove("catolog-Lezhnevka-show")
            catologSawmill.classList.remove("catolog-Sawmill-show")
            catologCharcoal.classList.remove("catolog-Charcoal-show")
            headingEuropoddons.classList.remove("heading-Europoddons-show")
            catologEuropoddons.classList.remove("catolog-Europoddons-show")
            headingError.classList.remove("heading-error-show")
            break;
        case "европоддоны":
            headingEuropoddons.classList.add("heading-Europoddons-show")
            catologEuropoddons.classList.add("catolog-Europoddons-show")
            wrapercatolog.classList.add("wraper-catolog-show")
            WraperOpenCertificate.classList.remove("wraper-open-certificate-show")
            HeadingAboutTheCompany.classList.remove("heading-about-the-company-show")
            HeadingDeliveryAndPayment.classList.remove("heading-delivery-and-payment-show")
            HeadingContacts.classList.remove("heading-contacts-show")
            headingCharcoal.classList.remove("heading-Charcoal-show")
            headinglezhnevka.classList.remove("heading-lezhnevka-show")
            headingSawmill.classList.remove("heading-Sawmill-show")
            headingLumber.classList.remove("heading-Lumber-show")
            catologLezhnevka.classList.remove("catolog-Lezhnevka-show")
            catologSawmill.classList.remove("catolog-Sawmill-show")
            catologCharcoal.classList.remove("catolog-Charcoal-show")
            catologLumber.classList.remove("catolog-Lumber-show")
            PhotoAboutTheCompanyBlockOfText.classList.remove("photo-about-the-company-block-of-text_show")
            WraperBlokDeliveryAndPayment.classList.remove("wraper-blok-delivery-and-payment-show")
            WraperContacts.classList.remove("wraper-contacts-show")
            headingError.classList.remove("heading-error-show")
            break;
        case "сертификат":
            WraperOpenCertificate.classList.add("wraper-open-certificate-show")
            HeadingAboutTheCompany.classList.add("heading-about-the-company-show")
            headingSawmill.classList.remove("heading-Sawmill-show")
            wrapercatolog.classList.remove("wraper-catolog-show")
            catologSawmill.classList.remove("catolog-Sawmill-show")
            PhotoAboutTheCompanyBlockOfText.classList.remove("photo-about-the-company-block-of-text_show")
            HeadingDeliveryAndPayment.classList.remove("heading-delivery-and-payment-show")
            HeadingContacts.classList.remove("heading-contacts-show")
            
            
            WraperBlokDeliveryAndPayment.classList.remove("wraper-blok-delivery-and-payment-show")
            WraperContacts.classList.remove("wraper-contacts-show")
            headinglezhnevka.classList.remove("heading-lezhnevka-show")
            catologLezhnevka.classList.remove("catolog-Lezhnevka-show")
            headingCharcoal.classList.remove("heading-Charcoal-show")
            catologCharcoal.classList.remove("catolog-Charcoal-show")
            headingLumber.classList.remove("heading-Lumber-show")
            catologLumber.classList.remove("catolog-Lumber-show")
            headingEuropoddons.classList.remove("heading-Europoddons-show")
            catologEuropoddons.classList.remove("catolog-Europoddons-show")
            break;
        default:
            headingError.classList.add("heading-error-show")
            // error.classList.add("wraper-Error-show")
            headingSawmill.classList.remove("heading-Sawmill-show")
            wrapercatolog.classList.remove("wraper-catolog-show")
            catologSawmill.classList.remove("catolog-Sawmill-show")
            PhotoAboutTheCompanyBlockOfText.classList.remove("photo-about-the-company-block-of-text_show")
            HeadingAboutTheCompany.classList.remove("heading-about-the-company-show")
            HeadingDeliveryAndPayment.classList.remove("heading-delivery-and-payment-show")
            HeadingContacts.classList.remove("heading-contacts-show")
            WraperBlokDeliveryAndPayment.classList.remove("wraper-blok-delivery-and-payment-show")
            WraperContacts.classList.remove("wraper-contacts-show")
            headinglezhnevka.classList.remove("heading-lezhnevka-show")
            catologLezhnevka.classList.remove("catolog-Lezhnevka-show")
            headingCharcoal.classList.remove("heading-Charcoal-show")
            catologCharcoal.classList.remove("catolog-Charcoal-show")
            WraperOpenCertificate.classList.remove("wraper-open-certificate-show")
            headingLumber.classList.remove("heading-Lumber-show")
            catologLumber.classList.remove("catolog-Lumber-show")
            headingEuropoddons.classList.remove("heading-Europoddons-show")
            catologEuropoddons.classList.remove("catolog-Europoddons-show")
    }



    return (inputText.value = "");
});

